---

- name: Update the Fragalysis Stack
  hosts: localhost
  tasks:
  - name: Run the fragalysis_stack role (update)
    ansible.builtin.include_role:
      name: fragalysis_stack
      tasks_from: update.yaml
