---
# Tasks required to 'shutdown' a deployed version of Fragalysis.
# This task removes the stack but leaves the database intact.
# It is used as a precursor to a database recovery.
#
# This playbook first ensures that the Fragalysis namespace exists
# and that an existing deployment exists - the user is first supposed
# to have deployed the stack before shutting it down.

- name: Prepare
  ansible.builtin.include_tasks: prep.yaml

# Go...

- name: Shutdown the stack
  module_defaults:
    group/k8s:
      kubeconfig: "{{ k8s_kubeconfig }}"
  block:
  - name: Get expected namespace ({{ stack_namespace }})
    kubernetes.core.k8s_info:
      kind: Namespace
      name: "{{ stack_namespace }}"
    register: ns_result

    # To 'shutdown' we remove: -
    # - Stack
    # - Django secret
    # And then, delete: -
    # - Media volume (optional)
  - name: Shutdown (if namespace exists)
    when: ns_result.resources | length > 0
    block:
    - name: Set django secret fact
          # These facts are required to remove the secret...
      ansible.builtin.set_fact:
        stack_django_secret_key_fact: "{{ stack_django_secret_key }}"
        stack_django_superuser_password_fact: "{{ stack_django_superuser_password }}"

    - name: Shutdown stack
      kubernetes.core.k8s:
        definition: "{{ lookup('template', item) }}"
        state: absent
        wait: yes
      loop:
      - statefulset-stack.yaml.j2
      - statefulset-worker.yaml.j2
      - deployment-beat.yaml.j2
      - secret-django.yaml.j2

    - name: Wait for stack to disappear
      kubernetes.core.k8s_info:
        kind: Pod
        name: stack-0
        namespace: "{{ stack_namespace }}"
      register: stack_result
      until: stack_result.resources | length == 0
      delay: 8
      retries: "{{ (wait_timeout | int / 8) | int }}"

    - name: Wait for worker to disappear
      kubernetes.core.k8s_info:
        kind: Pod
        name: worker-0
        namespace: "{{ stack_namespace }}"
      register: worker_result
      until: worker_result.resources | length == 0
      delay: 8
      retries: "{{ (wait_timeout | int / 8) | int }}"

    - name: Remove media volume
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'pvc-media.yaml.j2') }}"
        state: absent
        wait: yes
      when: stack_shutdown_remove_media_volume | bool

  # Done.
